<?php
    // Создаём заголовок страницы, который загрузится в layout
    $this->title = "Добавить заказ";
    $this->headTitle($this->title);
    
    echo "<div class='content-title'>";
    echo "<h3>Добавление сотрудника</h3>"; 
    echo "</div><!-- end content-title -->";
    
    // Выводим форму, полученную из контроллера
    echo "<div class='active-tickets' style='width: 300px; '>";
    echo $this->form ;
    echo "</div>";
    echo "<div class='main-menu-close'></div>";
?>
