<?php
    // Создаём заголовок страницы, который загрузится в layout
    $this->title = "Редактировать заказ";
    $this->headTitle($this->title);
    
    echo "<div class='content-title'>";
    echo "<h3>Редактирование заказа</h3>"; 
    echo "</div><!-- end content-title -->";
    
    // Выводим форму, полученную из контроллера
    echo "<div class='active-tickets' style='width: 300px; '>";
    echo $this->form ;
    echo "</div>";
    echo "<div class='main-menu-close'></div>";
?>

<div class="help-btn">
    <a href="/operator/information"><img src="/img/icon_help.png" alt="Справка" /></a>
</div>