<tr>
    <td><?php echo $this->escape($this->name);?></td>
    <td><?php echo $this->escape($this->contract);?></td>
    <td><?php echo $this->escape($this->phone);?></td>
    <td><?php echo $this->escape($this->namber_car);?></td>
    <td><?php echo $this->escape($this->list_car);?></td>
    <td style="text-align: center; " class="active-btn">
        <a href="<?php  echo $this->url(array('controller'=>'admin', 'action'=>'editcabdriver', 'id'=>$this->id));?>"><img src="img/icon_edit.png" alt="" /></a>
        <a href="<?php  echo $this->url(array('controller'=>'admin', 'action'=>'deletecabdriver', 'id'=>$this->id));?>"><img src="img/icon_del.png" alt="" /></a>
    </td> 
</tr>

