<tr>
    <td><?php echo $this->escape($this->name);?></td>
    <td><?php echo $this->escape($this->contract);?></td>
    <td><?php echo $this->escape($this->phone);?></td>
    <td><?php echo $this->escape($this->namber_car);?></td>
    <td colspan="2"><?php echo $this->escape($this->list_car);?></td>
    <td>
        <a href="<?php  echo $this->url(array('controller'=>'admin', 'action'=>'editcabdriver', 'id'=>$this->id));?>">Редактировать</a>
        <a href="<?php  echo $this->url(array('controller'=>'admin', 'action'=>'deletecabdriver', 'id'=>$this->id));?>">Удалить</a>
    </td> 
</tr>

