<tr>
    <td><?php echo $this->escape($this->name);?></td>
    <td><?php echo $this->escape($this->phone);?></td>
    <td><?php echo $this->escape($this->status);?></td>
    <?php 
    if($this->status == 'не работает'){ 
                $str = $this->url(array('controller'=>'operator', 'action'=>'onwork', 'id'=>$this->id)).'">Принять на рейсы';                 
            }
            else{
                $str = $this->url(array('controller'=>'operator', 'action'=>'offwork', 'id'=>$this->id)).'">Снять с рейсов';
            }
    
    if($this->status != 'занят'){
    echo"<td><a href=\"$str</a>        
    </td>";}?> 
</tr>

