<tr>
    <td><?php echo $this->escape($this->time_start);?></td>
    <td><?php echo $this->escape($this->address_start);?></td>
    <td><?php echo $this->escape($this->address_stop);?></td>
    <td><?php echo $this->escape($this->id_cab);?></td>
    <td><?php echo $this->escape($this->phone);?></td>
    <td><?php echo $this->escape($this->name_client);?></td>
    <td><?php echo $this->escape($this->phone_client);?></td>
    <td><?php echo $this->escape($this->status);?></td>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'operator', 'action'=>'appoint', 'id'=>$this->id,'id_cad'=>$this->id_cad));?>">Назначить таксиста</a>
        <a href="<?php echo $this->url(array('controller'=>'operator', 'action'=>'editorder', 'id'=>$this->id));?>">Редактировать</a>
        <a href="<?php echo $this->url(array('controller'=>'operator', 'action'=>'cancelorder', 'id'=>$this->id));?>">Отменить</a>
        <a href="<?php echo $this->url(array('controller'=>'operator', 'action'=>'closeorder', 'id'=>$this->id));?>">Закрыть</a>
    </td>
</tr>

