<tr>
    <td><?php echo $this->escape($this->name);?></td>
    <td><?php echo $this->escape($this->contract);?></td>
    <td><?php echo $this->escape($this->phone);?></td>
    <td><?php echo $this->escape($this->username);?></td>
    <td><?php echo $this->escape($this->password);?></td>
    <td><?php echo $this->escape($this->role);?></td>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'admin', 'action'=>'edituser', 'id'=>$this->id));?>">Редактировать</a>
        <a href="<?php echo $this->url(array('controller'=>'admin', 'action'=>'deleteuser', 'id'=>$this->id));?>">Удалить</a>
    </td>
</tr>

