<tr>
    <td><?php echo $this->escape($this->name);?></td>
    <td><?php echo $this->escape($this->contract);?></td>
    <td><?php echo $this->escape($this->phone);?></td>
    <td><?php echo $this->escape($this->username);?></td>
    <td><?php echo $this->escape($this->password);?></td>
    <td><?php echo $this->escape($this->role);?></td>
    <td style="text-align: center; " class="active-btn">
        <a href="<?php echo $this->url(array('controller'=>'admin', 'action'=>'edituser', 'id'=>$this->id));?>"><img src="img/icon_edit.png" alt="" /></a>
        <a href="<?php echo $this->url(array('controller'=>'admin', 'action'=>'deleteuser', 'id'=>$this->id));?>"><img src="img/icon_del.png" alt="" /></a>
    </td>
</tr>

