<?php
    $this->title = "Удаление таксиста";
    $this->headTitle($this->title);
?>
<p>Вы действительно хотите удалить таксиста 
    '<?php echo $this->escape($this->cabdriver['name']); ?>' с контрактом №
    <?php echo $this->escape($this->cabdriver['contract']); ?> и телефоном 
    <?php echo $this->escape($this->cabdriver['phone']); ?>?
</p>
<form action="<?php echo $this->url(array('action'=>'deletecabdriver')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->cabdriver['id']; ?>" />
        <input type="submit" name="del" value="Да" />
        <input type="submit" name="del" value="Нет" />
    </div>
</form>
