<?php
    $this->title = "Удаление сотрудника";
    $this->headTitle($this->title);
?>
<p>Вы действительно хотите удалить сотрудника 
    '<?php echo $this->escape($this->user['name']); ?>' с контрактом №
    <?php echo $this->escape($this->user['contract']); ?> и телефоном 
    <?php echo $this->escape($this->user['phone']); ?>?
</p>
<form action="<?php echo $this->url(array('action'=>'deleteuser')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->user['id']; ?>" />
        <input type="submit" name="del" value="Да" />
        <input type="submit" name="del" value="Нет" />
    </div>
</form>
